# Generated by Django 5.2.1 on 2025-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
